# 
# Workflow for reading .fit files in parallel
#

trigger: 
- master

jobs:

# Produces a list of ride files present in the blob container
# within Azure, using Python.
- job: generate_list_of_files
  steps:
  - script: |
      python -m pip install --upgrade pip
      pip install azure-storage-blob
      python $(Build.SourcesDirectory)/src/get_list_of_files_from_blob.py
    name: get_blob_files
    displayName: 'Create list of file in blob container'

# The previous job generates filenames of the files present
# in the blob container. Now process those files in parallel.
- job: process_ride_file
  dependsOn: generate_list_of_files
  strategy:
    maxParallel: 10
    matrix: $[ dependencies.generator.outputs['get_blob_files.files'] ]
  steps:
  - script: echo $(filename) # echos A or B depending on which leg is running
