# 
# Workflow for reading .fit files in parallel
#

jobs:
# Install Azure blob python package
- job: install_azure_blob
  steps:
    - task: CmdLine@2
      inputs:
        script: 'pip install azure-storage-blob'

# Produces a list of ride files present in the blob container
# within Azure, using Python.
- job: generate_list_of_files
  dependsOn: install_azure_blob
  steps:
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: $(Build.SourcesDirectory)/src/get_list_of_files_from_blob.py
  - script: python $(Build.SourcesDirectory)/src/get_list_of_files_from_blob.py
    name: get_blob_files

# The previous job generates filenames of the files present
# in the blob container. Now process those files in parallel.
- job: process_ride_file
  dependsOn: generate_list_of_files
  strategy:
    maxParallel: 10
    matrix: $[ dependencies.generator.outputs['get_blob_files.files'] ]
  steps:
  - script: echo $(filename) # echos A or B depending on which leg is running
